
import java.awt.Color;
import java.awt.event.KeyListener;
import java.io.File;
import static java.lang.Double.parseDouble;
import java.text.DecimalFormat;
import java.util.Random;
import java.sql.*;
import javax.sound.sampled.AudioInputStream;
import javax.sound.sampled.AudioSystem;
import javax.sound.sampled.Clip;
import javax.swing.JOptionPane;



/**
 *
 * @author Jonathan Vasallo
 */
public class Dice extends javax.swing.JFrame {

    /**
     * Creates new form Dice
     */
    private static String username;
    private String wrongSound = ".//Sounds//convertedWrongsound.wav";
    private String correctSound = ".//Sounds//convertedTrimCorrect.wav";
    private String CashSound = ".//Sounds//convertedWin.wav";
    private SoundEffect soundE = new SoundEffect();
    
    public Dice(String usernam) {
        this.username = usernam;
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jSlider1 = new javax.swing.JSlider();
        jButton1 = new javax.swing.JButton();
        jTextField1 = new javax.swing.JTextField();
        jTextField2 = new javax.swing.JTextField();
        jTextField3 = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jTextField4 = new javax.swing.JTextField();
        jTextField5 = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jProgressBar1 = new javax.swing.JProgressBar();
        jLabel6 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jTextField6 = new javax.swing.JTextField();
        jButton2 = new javax.swing.JButton();
        jLabel7 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(51, 0, 51));
        setMinimumSize(new java.awt.Dimension(710, 450));
        setResizable(false);
        addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                formKeyTyped(evt);
            }
        });
        getContentPane().setLayout(null);

        jSlider1.setBackground(new java.awt.Color(255, 51, 51));
        jSlider1.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        jSlider1.setOpaque(false);
        jSlider1.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                jSlider1StateChanged(evt);
            }
        });
        jSlider1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                jSlider1MouseReleased(evt);
            }
        });
        jSlider1.setMinimum(2);
        jSlider1.setMaximum(98);
        getContentPane().add(jSlider1);
        jSlider1.setBounds(70, 300, 530, 50);

        jButton1.setBackground(new java.awt.Color(0, 0, 0));
        jButton1.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jButton1.setForeground(new java.awt.Color(255, 153, 51));
        jButton1.setText("Start Game");
        jButton1.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(255, 153, 0), 1, true));
        jButton1.setBorderPainted(false);
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1);
        jButton1.setBounds(220, 40, 240, 50);

        jTextField1.setEditable(false);
        jTextField1.setBackground(new java.awt.Color(255, 204, 102));
        jTextField1.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jTextField1.setText("50");
        getContentPane().add(jTextField1);
        jTextField1.setBounds(130, 230, 110, 50);

        jTextField2.setEditable(false);
        jTextField2.setBackground(new java.awt.Color(255, 204, 102));
        jTextField2.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jTextField2.setText("1.95");
        jTextField2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField2ActionPerformed(evt);
            }
        });
        getContentPane().add(jTextField2);
        jTextField2.setBounds(290, 230, 110, 50);

        jTextField3.setBackground(new java.awt.Color(255, 204, 102));
        jTextField3.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jTextField3.setText("50");
        jTextField3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField3ActionPerformed(evt);
            }
        });
        getContentPane().add(jTextField3);
        jTextField3.setBounds(440, 230, 110, 50);

        jLabel1.setBackground(new java.awt.Color(0, 0, 0));
        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Roll Over");
        jLabel1.setOpaque(true);
        getContentPane().add(jLabel1);
        jLabel1.setBounds(130, 200, 110, 30);

        jLabel2.setBackground(new java.awt.Color(0, 0, 0));
        jLabel2.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2.setText("Multiplier");
        jLabel2.setOpaque(true);
        getContentPane().add(jLabel2);
        jLabel2.setBounds(290, 200, 110, 30);

        jLabel3.setBackground(new java.awt.Color(0, 0, 0));
        jLabel3.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel3.setText("% Chance to Win");
        jLabel3.setOpaque(true);
        getContentPane().add(jLabel3);
        jLabel3.setBounds(430, 200, 130, 30);

        jTextField4.setBackground(new java.awt.Color(255, 204, 102));
        jTextField4.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jTextField4.setText("0.00");
        jTextField4.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseMoved(java.awt.event.MouseEvent evt) {
                jTextField4MouseMoved(evt);
            }
        });
        jTextField4.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jTextField4MouseExited(evt);
            }
        });
        jTextField4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField4ActionPerformed(evt);
            }
        });
        jTextField4.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                jTextField4KeyTyped(evt);
            }
        });
        KeyListener[] keyListeners = jTextField4.getKeyListeners();
        jTextField4.removeKeyListener(keyListeners[0]);
        jTextField4.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                System.out.println(evt.getKeyChar()+ "char");
                if(evt.getKeyChar()=='1' || evt.getKeyChar()=='.' ||evt.getKeyChar()=='2'
                    || evt.getKeyChar()=='3' || evt.getKeyChar()=='4' || evt.getKeyChar()=='5' ||
                    evt.getKeyChar()=='6' || evt.getKeyChar()=='7' || evt.getKeyChar()=='8' ||
                    evt.getKeyChar()=='9' || evt.getKeyChar()=='0'){
                    jTextField4.validate();

                    updatePayout();
                    //System.out.println("worked");
                }else{
                    //System.out.println(evt.getKeyChar() + " Didnt Work");
                    evt.consume();
                }
                //evt.consume();
                //System.out.println("It worked");

            }
        });
        getContentPane().add(jTextField4);
        jTextField4.setBounds(130, 130, 190, 50);

        jTextField5.setEditable(false);
        jTextField5.setBackground(new java.awt.Color(255, 204, 102));
        jTextField5.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jTextField5.setText("0.00");
        getContentPane().add(jTextField5);
        jTextField5.setBounds(360, 130, 190, 50);

        jLabel4.setBackground(new java.awt.Color(0, 0, 0));
        jLabel4.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel4.setText("Bet Amount ");
        jLabel4.setOpaque(true);
        getContentPane().add(jLabel4);
        jLabel4.setBounds(130, 100, 190, 30);

        jLabel5.setBackground(new java.awt.Color(0, 0, 0));
        jLabel5.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel5.setText("Payout On Win");
        jLabel5.setOpaque(true);
        getContentPane().add(jLabel5);
        jLabel5.setBounds(360, 100, 190, 30);

        jProgressBar1.setMinimum(2);
        jProgressBar1.setValue(100);
        jProgressBar1.setBorder(javax.swing.BorderFactory.createMatteBorder(1, 1, 1, 1, new java.awt.Color(51, 255, 102)));
        jProgressBar1.setBorderPainted(false);
        jProgressBar1.setString("");
        jProgressBar1.setStringPainted(true);
        getContentPane().add(jProgressBar1);
        jProgressBar1.setBounds(70, 350, 530, 40);

        jLabel6.setText("Value Selected: 50");
        getContentPane().add(jLabel6);
        jLabel6.setBounds(280, 290, 120, 14);

        jLabel8.setForeground(new java.awt.Color(255, 255, 255));
        jLabel8.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel8.setText(username+"'s Balance $");
        getContentPane().add(jLabel8);
        jLabel8.setBounds(520, 20, 170, 30);

        upDateBalance();
        getContentPane().add(jTextField6);
        jTextField6.setBounds(550, 50, 110, 30);

        jButton2.setBackground(new java.awt.Color(255, 204, 102));
        jButton2.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jButton2.setText("Return To Hub");
        jButton2.setBorderPainted(false);
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton2);
        jButton2.setBounds(30, 30, 130, 40);

        jLabel7.setText("jLabel7");
        getContentPane().add(jLabel7);
        jLabel7.setBounds(-70, -280, 1880, 760);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        //Start game
        // subtract bet from balance
        String text1 = jTextField4.getText();
        String text2 = jTextField6.getText();
        double m1 = parseDouble(text1);
        double m2 = parseDouble(text2);
        
        if(m1<=m2 && m1<10000){ // person has enough to bet 
            
        
        Random rand = new Random();
        
        int random_integer = rand.nextInt(99 - 1) + 1;
        int valuePB = jSlider1.getValue();
        if(random_integer>valuePB){ // win
        jProgressBar1.setValue(random_integer);
        String val = String.valueOf(random_integer);
        jProgressBar1.setString(val);
        jProgressBar1.setBackground(Color.green);
        jProgressBar1.setForeground(Color.green);
        AddWinToBalance();
        
        } else if(random_integer<=valuePB){ // loss
        jProgressBar1.setValue(random_integer);
        String val = String.valueOf(random_integer);
        jProgressBar1.setString(val);
        jProgressBar1.setBackground(Color.red);
        jProgressBar1.setForeground(Color.red); 
        MinusLossToBalance();
        } else {
            System.out.println("error");
        }
        } // none of this happens if user cant start game 
        else{
            JOptionPane.showMessageDialog(null, "Insufficient Funds/ Maximum Bet is $10,000 ");
        }
       
       
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jTextField3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField3ActionPerformed
        // TODO add your handling code here:
        
    }//GEN-LAST:event_jTextField3ActionPerformed

    private void jSlider1StateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_jSlider1StateChanged
        // slider changing values
        
        int valueSlider = jSlider1.getValue();
        String slideVal = String.valueOf(valueSlider);
        jTextField1.setText(slideVal);
        String slideVal2 = String.valueOf(100-valueSlider);
        double numTempforMult= 100-valueSlider;
        jTextField3.setText(slideVal2);
        double Multiplier = (97.5/numTempforMult);
        DecimalFormat df = new DecimalFormat("#.##");
                double sendBackDecimal = Double.valueOf(df.format(Multiplier));
                String newerCashOut = String.valueOf(sendBackDecimal);
        
        jTextField2.setText(newerCashOut);
        
        jLabel6.setText("Value Selected: "+jTextField1.getText());
        
    }//GEN-LAST:event_jSlider1StateChanged

    private void jTextField2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField2ActionPerformed

    private void jTextField4KeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextField4KeyTyped
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField4KeyTyped

    private void jTextField4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField4ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField4ActionPerformed

    private void formKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_formKeyTyped
        // TODO add your handling code here:
       
    }//GEN-LAST:event_formKeyTyped

    private void jTextField4MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTextField4MouseExited
        // TODO add your handling code here:
        if(jTextField4.getText().equals("")){
            jTextField4.setText("0.00");
        }
        updatePayout();
         
    }//GEN-LAST:event_jTextField4MouseExited

    private void jSlider1MouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jSlider1MouseReleased
        // TODO add your handling code here:
        updatePayout();
    }//GEN-LAST:event_jSlider1MouseReleased

    private void jTextField4MouseMoved(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTextField4MouseMoved
        // TODO add your handling code here:
        if(jTextField4.getText().equals("")){
            jTextField4.setText("0.00");
        }
        updatePayout();
    }//GEN-LAST:event_jTextField4MouseMoved

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
        PlayingArea area1 = new PlayingArea(username);
        this.setVisible(false);
        area1.setVisible(true);
    }//GEN-LAST:event_jButton2ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Dice.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Dice.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Dice.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Dice.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Dice(username).setVisible(true);
            }
        });
    }
    
    public void updatePayout(){
        String convert = jTextField4.getText();
        
      
        double converted1 = parseDouble(convert);
        String convert2 = jTextField2.getText();
        double converted2 = parseDouble(convert2);
        double finalConvert = converted1*converted2;
        DecimalFormat df = new DecimalFormat("#.##");
        double sendBackDecimal = Double.valueOf(df.format(finalConvert));
        String newerCashOut = String.valueOf(sendBackDecimal);
        
        jTextField5.setText(newerCashOut);
    }
    
    public void upDateBalance(){
        try{
        String host = "jdbc:derby://localhost:1527/Accounts";
        String uName = "Allaccounts";
        String uPass = "accounts";
        java.sql.Connection con = DriverManager.getConnection(host,uName,uPass);
        java.sql.Statement stmt = con.createStatement();
        String SQL = "SELECT * FROM USERINFO";
        ResultSet rs = stmt.executeQuery(SQL);
        
        while (rs.next()){
         String userN = rs.getString("Username");
         double userB = rs.getDouble("Balance");
         DecimalFormat df = new DecimalFormat("#.##");
        double sendBackDecimal = Double.valueOf(df.format(userB));
        
         
         if(userN.equals(username)){
         String convert = String.valueOf(sendBackDecimal);
         jTextField6.setText(convert);
         
         }  
         
        } // end while 
        
        
        }catch(SQLException ex){
        System.out.println("error");    
        }
    }
    
    public void AddWinToBalance(){
        soundE.setFile(correctSound); // path to Correct.wav
        soundE.play();
        String wins = jTextField5.getText();
        double betNum = parseDouble(wins);
        DecimalFormat df = new DecimalFormat("#.##");
        double sendBackDecimal = Double.valueOf(df.format(betNum));
        double oldBal = 0;
        try {
            
            
            // somehow incorperate the database info here Username + Pass
            String host = "jdbc:derby://localhost:1527/Accounts";
            String uName = "Allaccounts";
            String uPass = "accounts";

            java.sql.Connection con = DriverManager.getConnection(host, uName, uPass);
            java.sql.Statement stmt = con.createStatement();
            String SQL2 = "SELECT * FROM USERINFO";
            ResultSet rs = stmt.executeQuery(SQL2);

            while (rs.next()) {
                String userN = rs.getString("Username");
                double userB = rs.getDouble("Balance");

                if (userN.equals(username)) {
                    oldBal = userB;
                    break;
                }

            }
            
            String SQL = "update userinfo set balance = ? where username = ?";
            //String query = "update users set num_points = ? where first_name = ?";
            PreparedStatement preparedStmt = con.prepareStatement(SQL);
            preparedStmt.setDouble(1, oldBal+sendBackDecimal);
            preparedStmt.setString(2, username);
            preparedStmt.executeUpdate();
            upDateBalance();
            validate();
            
            con.close();
            
            

        } catch (SQLException ex) {
            System.out.println("err");
            //Logger.getLogger(CasinoHome.class.getName()).log(Level.SEVERE, null, ex);
            //JOptionPane.showMessageDialog(null, "That Username has already been selected, choose another one");
            System.out.println(ex.getMessage());
        }
        
        
    }
    
    public void MinusLossToBalance(){
        soundE.setFile(wrongSound); // path to Correct.wav
        soundE.play();
        String wins = jTextField4.getText();
        double betNum = parseDouble(wins);
        DecimalFormat df = new DecimalFormat("#.##");
        double sendBackDecimal = Double.valueOf(df.format(betNum));
        double oldBal = 0;
        try {
            
            
            // somehow incorperate the database info here Username + Pass
            String host = "jdbc:derby://localhost:1527/Accounts";
            String uName = "Allaccounts";
            String uPass = "accounts";

            java.sql.Connection con = DriverManager.getConnection(host, uName, uPass);
            java.sql.Statement stmt = con.createStatement();
            String SQL2 = "SELECT * FROM USERINFO";
            ResultSet rs = stmt.executeQuery(SQL2);

            while (rs.next()) {
                String userN = rs.getString("Username");
                double userB = rs.getDouble("Balance");

                if (userN.equals(username)) {
                    oldBal = userB;
                    break;
                }

            }
            
            String SQL = "update userinfo set balance = ? where username = ?";
            //String query = "update users set num_points = ? where first_name = ?";
            PreparedStatement preparedStmt = con.prepareStatement(SQL);
            preparedStmt.setDouble(1, oldBal-sendBackDecimal);
            preparedStmt.setString(2, username);
            preparedStmt.executeUpdate();
            upDateBalance();
            validate();
            
            con.close();
            
            

        } catch (SQLException ex) {
            System.out.println("err");
            //Logger.getLogger(CasinoHome.class.getName()).log(Level.SEVERE, null, ex);
            //JOptionPane.showMessageDialog(null, "That Username has already been selected, choose another one");
            System.out.println(ex.getMessage());
        }
        
        
    }
    
    public class SoundEffect {

        Clip sound; // use clip to play sound effect

        public void setFile(String soundFileName) {
            try {
                File file = new File(soundFileName);
                AudioInputStream soundAIS = AudioSystem.getAudioInputStream(file);
                sound = AudioSystem.getClip();
                sound.open(soundAIS);

            } catch (Exception e) {

            }

        }

        public void play() {
            sound.setFramePosition(0);
            sound.start();
        }

    }
    
    

    
    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JProgressBar jProgressBar1;
    private javax.swing.JSlider jSlider1;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JTextField jTextField2;
    private javax.swing.JTextField jTextField3;
    private javax.swing.JTextField jTextField4;
    private javax.swing.JTextField jTextField5;
    private javax.swing.JTextField jTextField6;
    // End of variables declaration//GEN-END:variables
}
