
import static java.lang.Double.parseDouble;
import javax.swing.JTextField;
import java.sql.*;
import java.text.DecimalFormat;
import javax.swing.JOptionPane;


/**
 *
 * @author Jonathan Vasallo
 */
public class PlayingArea extends javax.swing.JFrame {

    /**
     * Creates new form PlayingArea
     */
    private static String username;

    public PlayingArea(String userN) {
        this.username = userN;
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel14 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jLabel12 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jButton3 = new javax.swing.JButton();
        jButton4 = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jButton6 = new javax.swing.JButton();
        jButton7 = new javax.swing.JButton();
        jButton8 = new javax.swing.JButton();
        jLabel10 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jTextField1 = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();

        jLabel14.setText("jLabel14");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMinimumSize(new java.awt.Dimension(860, 550));
        setResizable(false);
        getContentPane().setLayout(null);

        jLabel1.setFont(new java.awt.Font("Pacifico", 2, 48)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(204, 51, 255));
        jLabel1.setText("Game Hub      ");
        getContentPane().add(jLabel1);
        jLabel1.setBounds(260, 20, 300, 60);

        jLabel15.setFont(new java.awt.Font("Gabriola", 1, 24)); // NOI18N
        jLabel15.setForeground(new java.awt.Color(255, 255, 255));
        jLabel15.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jLabel15.setText("Roll The");
        getContentPane().add(jLabel15);
        jLabel15.setBounds(530, 180, 110, 50);

        jLabel16.setFont(new java.awt.Font("Gabriola", 1, 32)); // NOI18N
        jLabel16.setForeground(new java.awt.Color(255, 255, 255));
        jLabel16.setText("Dice");
        getContentPane().add(jLabel16);
        jLabel16.setBounds(560, 210, 180, 50);

        jLabel13.setIcon(new javax.swing.ImageIcon(getClass().getResource("/rollTheDice.PNG"))); // NOI18N
        jLabel13.setText("jLabel13");
        getContentPane().add(jLabel13);
        jLabel13.setBounds(527, 177, 110, 63);

        jButton1.setBackground(new java.awt.Color(255, 0, 204));
        jButton1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/playTow.PNG"))); // NOI18N
        jButton1.setBorderPainted(false);
        jButton1.setOpaque(false);
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1);
        jButton1.setBounds(375, 260, 140, 70);

        jButton2.setBackground(new java.awt.Color(255, 153, 102));
        jButton2.setFont(new java.awt.Font("ChunkFive Roman", 0, 36)); // NOI18N
        jButton2.setForeground(new java.awt.Color(255, 255, 255));
        jButton2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/playBoom.PNG"))); // NOI18N
        jButton2.setBorder(javax.swing.BorderFactory.createEtchedBorder(javax.swing.border.EtchedBorder.RAISED, new java.awt.Color(255, 153, 51), new java.awt.Color(255, 153, 51)));
        jButton2.setContentAreaFilled(false);
        jButton2.setOpaque(true);
        jButton2.setPreferredSize(new java.awt.Dimension(105, 50));
        jButton2.setRolloverEnabled(false);
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton2);
        jButton2.setBounds(228, 262, 130, 65);

        jLabel12.setFont(new java.awt.Font("Gabriola", 1, 40)); // NOI18N
        jLabel12.setForeground(new java.awt.Color(255, 255, 255));
        jLabel12.setText("Towers");
        getContentPane().add(jLabel12);
        jLabel12.setBounds(400, 190, 110, 70);

        jLabel11.setFont(new java.awt.Font("ChunkFive Roman", 0, 30)); // NOI18N
        jLabel11.setForeground(new java.awt.Color(255, 0, 255));
        jLabel11.setIcon(new javax.swing.ImageIcon(getClass().getResource("/towersnip.PNG"))); // NOI18N
        jLabel11.setOpaque(true);
        getContentPane().add(jLabel11);
        jLabel11.setBounds(390, 178, 110, 64);

        jButton3.setBackground(new java.awt.Color(204, 0, 204));
        jButton3.setFont(new java.awt.Font("Arial", 3, 12)); // NOI18N
        jButton3.setForeground(new java.awt.Color(255, 255, 255));
        jButton3.setText("Deposit");
        jButton3.setBorderPainted(false);
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton3);
        jButton3.setBounds(570, 10, 140, 23);

        jButton4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/playDice2.PNG"))); // NOI18N
        jButton4.setBorderPainted(false);
        jButton4.setOpaque(false);
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton4);
        jButton4.setBounds(520, 260, 130, 70);

        jLabel2.setText("Preview");
        getContentPane().add(jLabel2);
        jLabel2.setBounds(80, 110, 60, 14);

        jLabel3.setText("Preview");
        getContentPane().add(jLabel3);
        jLabel3.setBounds(290, 120, 60, 14);

        jLabel4.setText("Preview");
        getContentPane().add(jLabel4);
        jLabel4.setBounds(80, 330, 38, 14);

        jLabel5.setText("Preview");
        getContentPane().add(jLabel5);
        jLabel5.setBounds(140, 320, 50, 14);

        jLabel6.setForeground(new java.awt.Color(240, 240, 240));
        jLabel6.setText(username+"'s Balance");
        getContentPane().add(jLabel6);
        jLabel6.setBounds(740, 5, 130, 30);

        jButton6.setBackground(new java.awt.Color(204, 0, 204));
        jButton6.setFont(new java.awt.Font("Arial", 3, 12)); // NOI18N
        jButton6.setForeground(new java.awt.Color(255, 255, 255));
        jButton6.setText("Withraw To Bank");
        jButton6.setBorderPainted(false);
        jButton6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton6ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton6);
        jButton6.setBounds(570, 40, 140, 23);

        jButton7.setBackground(new java.awt.Color(0, 0, 0));
        jButton7.setFont(new java.awt.Font("Arial", 3, 12)); // NOI18N
        jButton7.setForeground(new java.awt.Color(204, 0, 204));
        jButton7.setText("Log out");
        jButton7.setBorderPainted(false);
        jButton7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton7ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton7);
        jButton7.setBounds(710, 450, 110, 23);

        jButton8.setBackground(new java.awt.Color(0, 0, 0));
        jButton8.setFont(new java.awt.Font("Arial", 3, 12)); // NOI18N
        jButton8.setForeground(new java.awt.Color(204, 0, 204));
        jButton8.setText("Close");
        jButton8.setBorderPainted(false);
        jButton8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton8ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton8);
        jButton8.setBounds(710, 480, 110, 23);

        jLabel10.setFont(new java.awt.Font("Gabriola", 1, 24)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(255, 255, 255));
        jLabel10.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel10.setText("BOMBS");
        getContentPane().add(jLabel10);
        jLabel10.setBounds(206, 193, 170, 50);

        jLabel9.setFont(new java.awt.Font("Blackout", 0, 30)); // NOI18N
        jLabel9.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel9.setIcon(new javax.swing.ImageIcon(getClass().getResource("/booooom3.PNG"))); // NOI18N
        jLabel9.setText("Bombs");
        jLabel9.setToolTipText("");
        jLabel9.setBorder(javax.swing.BorderFactory.createEtchedBorder(new java.awt.Color(255, 153, 51), new java.awt.Color(255, 153, 51)));
        getContentPane().add(jLabel9);
        jLabel9.setBounds(227, 173, 130, 70);

        jTextField1.setEditable(false);
        upDateBalance();
        jTextField1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField1ActionPerformed(evt);
            }
        });
        getContentPane().add(jTextField1);
        jTextField1.setBounds(730, 30, 110, 30);

        jLabel8.setFont(new java.awt.Font("Pacifico", 2, 48)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(102, 0, 102));
        jLabel8.setText("Game Hub  ");
        getContentPane().add(jLabel8);
        jLabel8.setBounds(256, 19, 280, 60);

        jLabel7.setIcon(new javax.swing.ImageIcon(getClass().getResource("/gamesCasino.jpg"))); // NOI18N
        getContentPane().add(jLabel7);
        jLabel7.setBounds(-220, -60, 1210, 690);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton7ActionPerformed
        // LOG OUT BUTTON 
        CasinoHome home = new CasinoHome();
        home.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_jButton7ActionPerformed

    private void jButton8ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton8ActionPerformed
        // Close button 
        System.exit(0);
    }//GEN-LAST:event_jButton8ActionPerformed

    private void jTextField1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField1ActionPerformed
        // Where the balance if user is visible 
    }//GEN-LAST:event_jTextField1ActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        //Game 1 button 
        TowersGame Tower = new TowersGame(username);
        Tower.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        //Deposit Button
        String depo = JOptionPane.showInputDialog("Enter Deposit Amount");
        double depositNum = parseDouble(depo);

        try {
            double oldBal = 0;
            // somehow incorperate the database info here Username + Pass
            String host = "jdbc:derby://localhost:1527/Accounts";
            String uName = "Allaccounts";
            String uPass = "accounts";

            Connection con = DriverManager.getConnection(host, uName, uPass);
            Statement stmt = con.createStatement();
            String SQL2 = "SELECT * FROM USERINFO";
            ResultSet rs = stmt.executeQuery(SQL2);

            while (rs.next()) {
                String userN = rs.getString("Username");
                double userB = rs.getDouble("Balance");

                if (userN.equals(username)) {
                    oldBal = userB;
                    break;
                }

            }
            
            String SQL = "update userinfo set balance = ? where username = ?";
            //String query = "update users set num_points = ? where first_name = ?";
            PreparedStatement preparedStmt = con.prepareStatement(SQL);
            preparedStmt.setDouble(1, oldBal+depositNum);
            preparedStmt.setString(2, username);
            preparedStmt.executeUpdate();
            upDateBalance();
            validate();
            
            con.close();
            

        } catch (SQLException ex) {
            System.out.println("err");
            //Logger.getLogger(CasinoHome.class.getName()).log(Level.SEVERE, null, ex);
            //JOptionPane.showMessageDialog(null, "That Username has already been selected, choose another one");
            System.out.println(ex.getMessage());
        }
    }//GEN-LAST:event_jButton3ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
        BombsGame Bomb = new BombsGame(username);
        Bomb.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
        // TODO add your handling code here:
        Dice dicer = new Dice(username);
        dicer.setVisible(true);
        this.setVisible(false);
        
    }//GEN-LAST:event_jButton4ActionPerformed

    private void jButton6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton6ActionPerformed
    String temp = JOptionPane.showInputDialog("Enter the amount to want to take out from your balance to send to your bank.");
        ToBankFromBalance(temp);        
    }//GEN-LAST:event_jButton6ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(PlayingArea.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(PlayingArea.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(PlayingArea.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(PlayingArea.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new PlayingArea(username).setVisible(true);
            }
        });
    }
    
    public void upDateBalance(){
        try{
        String host = "jdbc:derby://localhost:1527/Accounts";
        String uName = "Allaccounts";
        String uPass = "accounts";
        Connection con = DriverManager.getConnection(host,uName,uPass);
        Statement stmt = con.createStatement();
        String SQL = "SELECT * FROM USERINFO";
        ResultSet rs = stmt.executeQuery(SQL);
        
        while (rs.next()){
         String userN = rs.getString("Username");
         double userB = rs.getDouble("Balance");
         DecimalFormat df = new DecimalFormat("#.##");
        double sendBackDecimal = Double.valueOf(df.format(userB));
        
         
         if(userN.equals(username)){
         String convert = String.valueOf(sendBackDecimal);
         jTextField1.setText("$"+convert);
         
         }  
         
        } // end while 
        
        
        }catch(SQLException ex){
        System.out.println("error");    
        }
    }
    
    public void ToBankFromBalance(String amt){
        
        String wins = amt;
        double betNum = parseDouble(wins);
        DecimalFormat df = new DecimalFormat("#.##");
        double sendBackDecimal = Double.valueOf(df.format(betNum));
        double oldBal = 0;
        try {
            
            
            // somehow incorperate the database info here Username + Pass
            String host = "jdbc:derby://localhost:1527/Accounts";
            String uName = "Allaccounts";
            String uPass = "accounts";

            Connection con = DriverManager.getConnection(host, uName, uPass);
            Statement stmt = con.createStatement();
            String SQL2 = "SELECT * FROM USERINFO";
            ResultSet rs = stmt.executeQuery(SQL2);

            while (rs.next()) {
                String userN = rs.getString("Username");
                double userB = rs.getDouble("Balance");

                if (userN.equals(username)) {
                    oldBal = userB;
                    break;
                }

            }
            
            String SQL = "update userinfo set balance = ? where username = ?";
            //String query = "update users set num_points = ? where first_name = ?";
            PreparedStatement preparedStmt = con.prepareStatement(SQL);
            preparedStmt.setDouble(1, oldBal-sendBackDecimal);
            preparedStmt.setString(2, username);
            preparedStmt.executeUpdate();
            upDateBalance();
            validate();
            
            con.close();
            
            

        } catch (SQLException ex) {
            System.out.println("err");
            //Logger.getLogger(CasinoHome.class.getName()).log(Level.SEVERE, null, ex);
            //JOptionPane.showMessageDialog(null, "That Username has already been selected, choose another one");
            System.out.println(ex.getMessage());
        }
        
        
    }


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButton6;
    private javax.swing.JButton jButton7;
    private javax.swing.JButton jButton8;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JTextField jTextField1;
    // End of variables declaration//GEN-END:variables
}
